### ISSUE TITLE
PlanarPts from the keyPtsData is empty

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#14]
I realized that the variable PlanarPts is initialized as an empty np.array(), these empty array values are stored in the keypts (*.bin.mat) files.

![image](https://user-images.githubusercontent.com/12661590/99722971-cd7c8580-2ab1-11eb-8af8-6c7720e28e8d.png)

How can I populate this values stored in the keypts files because it is needed in the refinePoses.py, here:
`
    PlanarPts1_ = copy.deepcopy(PlanarPts1)
`
`
    PlanarPts1_[:, 0:3] = np.array(((np.dot(oriRelR, PlanarPts1[:, 0:3].T) + oriRelT).T), dtype=np.float32)
`

How can I resolve this?

**Comment by SRainGit** [comment]
Uncomment the last half part in function `GetKeyPtsByAE` in `SphericalRing.py`. Because the process is very low, I commented them out when I released the code. I will appreciate it if you can find a faster method to estimate planar points.
By the way, if you run through the initial odometry, you can check the result by setting the below codes in `RefinePoses.py`:
```
iShowResult = 1
iShowMatchingResult = 0

# enables: 0, disable;    1, enable;    2, read from file.
iGroundTruth = 1
iEstimatedOdometry = 2
iDejump = 0
iRefineOdometry = 0
iCloseLoop = 0

# refine option for choosing key frame: 0, frame to frame; 1, by selecting keyframe
refineOption = 0
# refineOption = 1


ErrorAnalysis = 1
AllErrorAngles = np.zeros((1,1), dtype=np.float32)
AllErrorTs = np.zeros((1,1), dtype=np.float32)

#   0, 2     2, 5     5, 8    8, 11    11, 14    14, 18     18, 20     20, 22
# prepare data path
for iSequence in range(0, 11, 1):
```
