### ISSUE TITLE
Question about the pose refinement.

### ISSUE THREAD

**Issue by XuyangBai** [SRainGit/CAE-LO#2]
Hi, Thanks for sharing. I have some questions regards the pose refinement step. In the paper, you claimed that it is based on ICP and you only use a smaller number of EIPs to reduce the computation cost.  In my view, the reason why ICP can achieve highly accurate results is that it uses dense point cloud to build the correspondences, while the initial odometry got by RANSAC is estimated using sparse keypoint correspondences. So I am really confused about this step. How many EIPs you are using for ICP?  And have you done some ablation studies on the number of EIPs vs. the error decrease?

Thank you for your time.

**Comment by SRainGit** [comment]
> Hi, Thanks for sharing. I have some questions regards the pose refinement step. In the paper, you claimed that it is based on ICP and you only use a smaller number of EIPs to reduce the computation cost. In my view, the reason why ICP can achieve highly accurate results is that it uses dense point cloud to build the correspondences, while the initial odometry got by RANSAC is estimated using sparse keypoint correspondences. So I am really confused about this step. How many EIPs you are using for ICP? And have you done some ablation studies on the number of EIPs vs. the error decrease?
> 
> Thank you for your time.

Hi! Thanks for your interest in my work and sorry for the part that confuses you. The ablation studies were not shown in the preprint version currently.

The basic solution of using feature-based frame to frame matching to get an initial odometry and using full point clouds of the keyframes to refine the initial odometry will be easy to be understood. In our work, the use of EIPs is to decrease the computation on the refinement.

EIPs are obtained in the spherical ring structured data by picking up valid pixels around the detected interest points (pixels). The parameter ℎ𝐸 is fixed while the number of EIPs various. Because:
1) the valid pixels surrounding one interest point is not fixed;
2) sometimes there are overlaps between neighboring areas of interest points.

I hope that explains well.

**Comment by XuyangBai** [comment]
Thanks a lot. That makes sense.
